<a href="https://colab.research.google.com/github/Ibreez16/numpy_learning/blob/main/NumPy_Prac_(3_5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


In [ ]:
import numpy as np
a = np.array([[92, 90, 74],[ 6, 63, 93],[15, 93, 96],[70, 60, 48]])
print(a)


[[92 90 74]
 [ 6 63 93]
 [15 93 96]
 [70 60 48]]


In [ ]:
np.sort(a)

array([[74, 90, 92],
       [ 6, 63, 93],
       [15, 93, 96],
       [48, 60, 70]])

In [ ]:
a[:,1].argsort()

array([3, 1, 0, 2])

In [ ]:
a[a[:,1].argsort()]

array([[70, 60, 48],
       [ 6, 63, 93],
       [92, 90, 74],
       [15, 93, 96]])

In [ ]:
a[np.max(a, axis=1).argsort()]

array([[70, 60, 48],
       [92, 90, 74],
       [ 6, 63, 93],
       [15, 93, 96]])

In [ ]:
a[np.max(a, axis=1).argsort()[::-1]]

array([[15, 93, 96],
       [ 6, 63, 93],
       [92, 90, 74],
       [70, 60, 48]])

In [ ]:
np.sort(a, axis = None).reshape(a.shape)

array([[ 6, 15, 48],
       [60, 63, 70],
       [74, 90, 92],
       [93, 93, 96]])

See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [ ]:
# code here

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

In [ ]:
arr = np.random.randint(1,100,(5,4))
arr

array([[47, 84,  1, 61],
       [52, 31, 87, 94],
       [87, 47, 88, 20],
       [61, 70, 68, 44],
       [29,  1, 57, 49]])

In [ ]:
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])
extra_subject = np.array([41, 87, 72, 36, 92])
marks = np.append(marks, extra_subject.reshape(5,1), axis = 1)

In [ ]:
marks.shape

(5, 5)

In [ ]:
rec1 = np.array([[77, 83, 98, 95, 89]])
rec2 = np.array([[92, 71, 52, 61, 53]])
marks = np.concat((marks, rec1, rec2), axis = 0)
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [ ]:
np.sum(marks, axis = 1).shape

(9,)

In [ ]:
marks = np.append(marks, np.sum(marks, axis = 1).reshape(9,1), axis = 1)
marks

array([[ 13,  10,   9,  33,  41, 106, 212],
       [ 63,  46,  90,  42,  87, 328, 656],
       [ 39,  76,  13,  29,  72, 229, 458],
       [ 82,   9,  29,  78,  36, 234, 468],
       [ 67,  61,  59,  36,  92, 315, 630],
       [ 77,  83,  98,  95,  89, 442, 884],
       [ 92,  71,  52,  61,  53, 329, 658],
       [ 77,  83,  98,  95,  89, 442, 884],
       [ 92,  71,  52,  61,  53, 329, 658]])

In [ ]:
Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

In [ ]:
marks[marks[:,-1].argsort()][::-1]

array([[ 77,  83,  98,  95,  89, 442, 884],
       [ 77,  83,  98,  95,  89, 442, 884],
       [ 92,  71,  52,  61,  53, 329, 658],
       [ 92,  71,  52,  61,  53, 329, 658],
       [ 63,  46,  90,  42,  87, 328, 656],
       [ 67,  61,  59,  36,  92, 315, 630],
       [ 82,   9,  29,  78,  36, 234, 468],
       [ 39,  76,  13,  29,  72, 229, 458],
       [ 13,  10,   9,  33,  41, 106, 212]])

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [ ]:
# code here

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [ ]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
np.unique(arr, axis = 0)

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

In [ ]:
np.unique(arr, axis = 1)

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

###`Q-4:` Flip given 2-D array along both axes at the same time.

In [ ]:
arr

array([[1, 2, 3, 3, 1, 1],
       [0, 9, 1, 2, 8, 8],
       [1, 2, 3, 8, 8, 8],
       [1, 2, 3, 3, 1, 1]])

In [ ]:
# code here
np.flip(arr)

array([[1, 1, 3, 3, 2, 1],
       [8, 8, 8, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [1, 1, 3, 3, 2, 1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [ ]:
# code here
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])
X = 6
np.where(arr > X)

(array([1, 1, 3, 3]), array([0, 2, 0, 1]))

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [2]:
# These arrays are given.
import numpy as np
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [6]:
# code here
print(arr1)
print(arr2)
print(arr3)
array_of_arrays = np.concat((arr1, arr2, arr3), axis = 0)
array_of_arrays

[0 1 2]
[3 4 5 6]
[7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [8]:
# code here
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
arr

array([[448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
        387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
        277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
        997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
        645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
        957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
        244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
        270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265,
        503, 320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123,
        946, 587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514,
        296, 879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658,
        528, 395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711,
        800, 976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490,
        803, 621, 453, 193, 607, 677, 637, 728, 724

In [14]:
np.max(arr)

np.int64(998)

In [15]:
np.min(arr)

np.int64(103)

In [12]:
np.argmax(arr)

np.int64(102)

In [13]:
np.argmin(arr)

np.int64(66)

In [11]:
np.delete(arr,[np.argmax(arr), np.argmin(arr)])

array([448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
       387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
       277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
       997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
       645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
       957, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464, 244,
       782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771, 270,
       308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 265, 503, 320,
       230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946, 587,
       227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296, 879,
       575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528, 395,
       525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800, 976,
       786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803, 621,
       453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 194, 76

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [18]:
# code here
arr = np.random.randint(100,700,50)
np.clip(arr, a_min = 100, a_max = 200)


array([200, 200, 151, 200, 200, 200, 200, 148, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 189, 200, 200, 116, 142, 200, 193, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 157, 200, 200, 200])

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [29]:
# code here
arr = np.round(np.random.random((1,100)), 3)
arr

array([[0.563, 0.413, 0.015, 0.976, 0.368, 0.133, 0.443, 0.331, 0.217,
        0.08 , 0.608, 0.198, 0.442, 0.95 , 0.745, 0.982, 0.961, 0.279,
        0.866, 0.181, 0.149, 0.323, 0.086, 0.337, 0.813, 0.164, 0.943,
        0.562, 0.861, 0.256, 0.583, 0.67 , 0.555, 0.347, 0.617, 0.52 ,
        0.443, 0.173, 0.307, 0.988, 0.761, 0.889, 0.088, 0.71 , 0.403,
        0.71 , 0.654, 0.032, 0.357, 0.493, 0.654, 0.58 , 0.714, 0.427,
        0.859, 0.448, 0.537, 0.865, 0.201, 0.149, 0.835, 0.305, 0.103,
        0.584, 0.865, 0.735, 0.281, 0.748, 0.642, 0.845, 0.333, 0.308,
        0.7  , 0.347, 0.654, 0.179, 0.869, 0.093, 0.535, 0.534, 0.406,
        0.217, 0.378, 0.107, 0.245, 0.633, 0.273, 0.018, 0.37 , 0.147,
        0.807, 0.881, 0.043, 0.103, 0.977, 0.023, 0.976, 0.033, 0.007,
        0.641]])

In [36]:
if (np.percentile(arr, 0) == np.min(arr)):
  print("Yes", np.min(arr))
if (np.percentile(arr,100) == np.max(arr)):
  print("Yes", np.max(arr))
diff = np.percentile(arr, 51) - np.percentile(arr, 50)
print(np.percentile(arr, 51))
print(np.percentile(arr, 50))
print("Diff btw 51th and 50th percentile:", diff )

Yes 0.007
Yes 0.988
0.44545
0.443
Diff btw 51th and 50th percentile: 0.0024500000000000077
