<a href="https://colab.research.google.com/github/Ibreez16/numpy_learning/blob/main/NumPy_Practice_(1_5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [ ]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
#Code here
a = np.array([0,0,0,0,1,0,0,0,0,0])

b = np.zeros(10, dtype = int)
b[4] = 1

print(a)
print(b)

[0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
#Code here
a = int(input('Enter a number: '))
b = int(input('Enter a number: '))

c = np.ceil(np.random.random((a, b)) * 10)
print(c)
print(np.average(c))

Enter a number: 2
Enter a number: 2
[[ 5.  6.]
 [10. 10.]]
7.75


2###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
#Code here
a = int(input('Enter a number: '))
b = int(input('Enter a number: '))

c = np.zeros((a,b), dtype = int)
print(c)
c[0, :] = 1
c[-1, :] = 1
c[:, 0] = 1
c[:, -1] = 1
print(c)

Enter a number: 2
Enter a number: 2
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
#Code here
a = np.random.random(10)
print(a)

[0.32335538 0.93430874 0.5255227  0.05214005 0.28299593 0.09603843
 0.72428542 0.68531864 0.04191509 0.36225719]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Code here
a = np.identity(3)
a
#identity matrices must be a square matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
#Code here
a = np.arange(5).reshape(1,5).repeat(5, axis = 0)
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
#code here
a = np.random.randint(1,100, size = (10,2))
point = np.array([2,3])

distance = np.sqrt(np.sum((a - point) ** 2, axis = 1)).astype(int)
distance

array([ 94, 107,  79,  70,  37,  77,  85,  63,  68,  64])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
#Code here
(1, 5, 4)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
#Code here
a = np.array([1,2,3,4,-8,-10])
a[::-1].astype(float)

array([-10.,  -8.,   4.,   3.,   2.,   1.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
#Code here
a = np.array([[1, 2],[1,2]])
a.size

4

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



In [ ]:
def softmax(arr):
  if arr.ndim != 1:
    raise ValueError("not 1d array")
  else:
    softmax_output = np.exp(arr) / np.sum(np.exp(arr))
    return softmax_output


a = np.array([86.03331084, 37.7285648, 48.64908087, 87.16563062, 38.40852563, 37.20006318])
softmax(a)

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



In [ ]:
def vertical_stack(*args):
  for arr in args:
    if isinstance(arr, np.ndarray):
      return np.vstack(args)
    else:
      raise TypeError("not numpy array")


a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
b = np.array([[1,1,1,1,1],[1,1,1,1,1]])

vertical_stack(a,b)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
#Coder here

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



In [ ]:
from datetime import datetime, timedelta
import numpy as np
def date_array (start_time, end_time):
  if not (isinstance(start_time, str) and isinstance(end_time, str)):
    raise TypeError("Type is not ok")
  else:
    start = datetime.strptime(start_time, "%Y-%m-%d").date()
    end = datetime.strptime(end_time, "%Y-%m-%d").date()

    delta = (end - start).days
    dates = [(start + timedelta(days=i)).strftime("%Y-%m-%d") for i in range(delta + 1)]
    return np.array(dates)

date_array('2026-1-14', '2026-1-19')

array(['2026-01-14', '2026-01-15', '2026-01-16', '2026-01-17',
       '2026-01-18', '2026-01-19'], dtype='<U10')

In [ ]:
date_array

<function __main__.date_array(start_time, end_time)>

**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here

###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
#code here
a = np.arange(1,10).reshape(3,3)
mean = a - a.mean(axis = 1, keepdims=True)
print(a)
print(mean)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
#Code here

In [ ]:
a = np.arange(1,10).reshape(3,3)
print(a)
b = a[0:, 0].copy()
a[0:, 0] = a[0:, 2]
a[0:, 2] = b
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
a = np.arange(1,10).reshape(3,3)
print(a)
a[:, [0, 2]] = a[:, [2, 0]]
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
#Code here

In [5]:
import numpy as np
a = np.arange(9).reshape(3,3)
a[a % 2 != 0] = -1
a

array([[ 0, -1,  2],
       [-1,  4, -1],
       [ 6, -1,  8]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here

In [8]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
c = np.maximum(a,b)
c

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [15]:
def normalise(arr):
  norm = (arr - np.min(arr))/(np.max(arr) - np.min(arr))
  return norm
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
print(arr1)
c = arr1[0:,0::2]
print(c)
normalise(c)

[[ 690 4590 7301 4588 6103]
 [4566 9941  552 7192 4318]
 [3732 8447 5107 3707 7983]
 [1437 4150 6809 3354    3]
 [3858 4467 8837 2586 9455]
 [7114 2212 2300 4456 2498]
 [1792 6448 2426 9146 5388]
 [5258 8598 1545 3823 2183]]
[[ 690 7301 6103]
 [4566  552 4318]
 [3732 5107 7983]
 [1437 6809    3]
 [3858 8837 9455]
 [7114 2300 2498]
 [1792 2426 5388]
 [5258 1545 2183]]


array([[0.07268303, 0.77211172, 0.64536606],
       [0.48275497, 0.05808295, 0.45651714],
       [0.39451968, 0.53999154, 0.84426576],
       [0.15171392, 0.72005925, 0.        ],
       [0.40785019, 0.93461701, 1.        ],
       [0.75232755, 0.24301735, 0.2639653 ],
       [0.18927211, 0.25634786, 0.56972069],
       [0.55596699, 0.16314008, 0.23063902]])

In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2939, 1694, 6680, 8865, 2684],
       [4066, 4573,  327, 6525,  851],
       [5997, 7481, 2315, 5863, 9615],
       [7821, 1225, 9138, 1114, 4885],
       [7715, 8046, 9105, 3935, 3182],
       [8842, 4836, 2705, 3751, 3800],
       [4132, 1400, 7844, 9471, 7526],
       [2749, 2624, 6900, 1576, 7515]])

In [ ]:
#Code here

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [35]:
#Code here
def largest_item (arr, n):
  if n <= len(arr):
    arr1 = arr
    for i in range(n):
      num = np.max(arr1)
      arr1 = arr1[arr1 != num]
    return int(num)
arr = np.array([12,34,40,7,1,0])
largest_item(arr, 3)

12

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [33]:
#code here
a = np.array([1,2,3])
b = np.repeat(a,3)
c = np.tile(a,3)
d = np.concat((b,c))
d

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])