<a href="https://colab.research.google.com/github/Ibreez16/numpy_learning/blob/main/NumPy_Practice_(2_5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###`Q-1:` Find the nearest element in the array to a given integer.
```
Ex:-
a=23 and array - [10 17 24 31 38 45 52 59].
Nearest element is 24
```
Hint: Read about this function `argmin()`

In [ ]:
# code here
import numpy as np
a = np.array([10, 17, 24, 31, 38, 45, 52, 59])
n = 2
print(a[np.argmin(np.abs(a-n))])

10


###`Q-2:` Replace multiples of 3 or 5 as 0 in the given array.
```
arr=[1 2 3 4 5 6 7 9]

result-> [1 2 0 4 0 0 7 0]
```

In [ ]:
# code here
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 9])
arr1[(arr1 % 3 == 0) | (arr1 % 5 == 0)] = 0
arr1

array([1, 2, 0, 4, 0, 0, 7, 0])

###`Q-3:` Use Fancy Indexing.
1. Double the array elements at  given indexes
```
arr = np.arrange(10)
indexes = [0,3,4,9]
```
Result -> `[ 0  1  2  6  8  5  6  7  8 18]`

2. Using a given array make a different array as in below example
```
array = [1,2,3]
result array -> [1 1 1 2 2 2 3 3 3]
```
* Internal-repetion should be as length of the array.

Hint:
```
if a is an array
a = [2,4]
a[[1,1,0,1]] will result in-> [4 4 2 4]
```

In [ ]:
# code here
import numpy as np
arr = np.arange(10)
indexes = [0, 3, 4, 9]
arr[indexes] = arr[indexes] + arr[indexes]
arr

array([ 0,  1,  2,  6,  8,  5,  6,  7,  8, 18])

In [ ]:
array = np.array([1, 2, 3])
np.repeat(array, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

###`Q-4:` Your are given an array which is havig some nan value. You job is to fill those nan values with most common element in the array.
```
arr=np.array([[1,2,np.nan],[4,2,6],[np.nan,np.nan,5]])

```

In [ ]:
import numpy as np

arr = np.array([[1,7,np.nan],
                [4,7,6],
                [np.nan,np.nan,5]])


# Step 1: remove NaNs
valid = arr[~np.isnan(arr)]

# Step 2: find most common value
values, counts = np.unique(valid, return_counts=True)
most_common = values[np.argmax(counts)]

# Step 3: replace NaNs
arr[np.isnan(arr)] = most_common

arr


array([[1., 7., 7.],
       [4., 7., 6.],
       [7., 7., 5.]])

In [ ]:
# code here
import numpy as np
arr1=np.array([[1,2,np.nan],[4,2,6],[np.nan,np.nan,5]])
print(np.argmax(arr1))
print(arr1[np.isnan(arr1)])
arr1[np.isnan(arr1)] = np.argmax(arr1)


2
[nan nan nan]


In [ ]:
arr = np.array([[1,2,np.nan],
                [4,2,6],
                [np.nan,np.nan,5]])

arr[np.isnan(arr)] = 999
arr


array([[  1.,   2., 999.],
       [  4.,   2.,   6.],
       [999., 999.,   5.]])

In [ ]:
arr = np.array([np.nan])
arr[np.isnan(arr)] = np.argmax(arr)
arr


array([0.])

### `Q-5:` Write a NumPy program

- to find the missing data in a given array. Return a boolean matrix.
- also try to fill those missing values with 0. For that, you can use `np.nan_to_num(a)`

```python
import numpy as np

np.array([[3, 2, np.nan, 1],
          [10, 12, 10, 9],
          [5, np.nan, 1, np.nan]])
```

In [5]:
# code here
import numpy as np

arr = np.array([[3, 2, np.nan, 1],
          [10, 12, 10, 9],
          [5, np.nan, 1, np.nan]])
arr_mask = np.isnan(arr)
aa1 = np.nan_to_num(arr, nan = 0)
aa1

array([[ 3.,  2.,  0.,  1.],
       [10., 12., 10.,  9.],
       [ 5.,  0.,  1.,  0.]])